"""empty message

Revision ID: cd76e656f9d4
Revises: 
Create Date: 2022-02-21 21:39:07.045565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd76e656f9d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lanzhou_pre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district', sa.String(length=10), nullable=False),
    sa.Column('furnish', sa.String(length=10), nullable=False),
    sa.Column('facing', sa.String(length=10), nullable=False),
    sa.Column('floor', sa.String(length=10), nullable=False),
    sa.Column('room', sa.Integer(), nullable=False),
    sa.Column('hall', sa.Integer(), nullable=False),
    sa.Column('elevator', sa.String(length=10), nullable=False),
    sa.Column('bui_category', sa.String(length=10), nullable=False),
    sa.Column('property', sa.String(length=10), nullable=False),
    sa.Column('school', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CRIM', sa.Float(), nullable=False),
    sa.Column('ZN', sa.Float(), nullable=False),
    sa.Column('INDUS', sa.Float(), nullable=False),
    sa.Column('CHAS', sa.Integer(), nullable=False),
    sa.Column('NOX', sa.Float(), nullable=False),
    sa.Column('RM', sa.Float(), nullable=False),
    sa.Column('AGE', sa.Float(), nullable=False),
    sa.Column('DIS', sa.Float(), nullable=False),
    sa.Column('RAD', sa.Float(), nullable=False),
    sa.Column('TAX', sa.Float(), nullable=False),
    sa.Column('PTRATIO', sa.Float(), nullable=False),
    sa.Column('B', sa.Float(), nullable=False),
    sa.Column('LSTAT', sa.Float(), nullable=False),
    sa.Column('MEDV', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'SECRET', 'UNKNOW', name='genderenum'), nullable=False),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.Column('introduce', sa.TEXT(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone')
    )
    op.drop_table('lanzhou_housing')
    op.drop_table('real_predicted')
    op.drop_table('housing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housing',
    sa.Column('ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CRIM', mysql.FLOAT(), nullable=True),
    sa.Column('ZN', mysql.FLOAT(), nullable=True),
    sa.Column('INDUS', mysql.FLOAT(), nullable=True),
    sa.Column('CHAS', mysql.FLOAT(), nullable=True),
    sa.Column('NOX', mysql.FLOAT(), nullable=True),
    sa.Column('RM', mysql.FLOAT(), nullable=True),
    sa.Column('AGE', mysql.FLOAT(), nullable=True),
    sa.Column('DIS', mysql.FLOAT(), nullable=True),
    sa.Column('RAD', mysql.FLOAT(), nullable=True),
    sa.Column('TAX', mysql.FLOAT(), nullable=True),
    sa.Column('PTRATIO', mysql.FLOAT(), nullable=True),
    sa.Column('B', mysql.FLOAT(), nullable=True),
    sa.Column('LSTAT', mysql.FLOAT(), nullable=True),
    sa.Column('house_price', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('real_predicted',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('y_test', mysql.FLOAT(), nullable=True),
    sa.Column('prediction', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('lanzhou_housing',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('district', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('furnish', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('facing', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('floor', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('room', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hall', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('elevator', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bui_category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('property', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('school', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('area', mysql.FLOAT(), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    op.drop_table('prediction')
    op.drop_table('lanzhou_pre')
    # ### end Alembic commands ###
