"""empty message

Revision ID: 2078ba9273b8
Revises: 
Create Date: 2022-02-10 16:43:29.244040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2078ba9273b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CRIM', sa.Float(), nullable=False),
    sa.Column('ZN', sa.Float(), nullable=False),
    sa.Column('INDUS', sa.Float(), nullable=False),
    sa.Column('CHAS', sa.Integer(), nullable=False),
    sa.Column('NOX', sa.Float(), nullable=False),
    sa.Column('RM', sa.Float(), nullable=False),
    sa.Column('AGE', sa.Float(), nullable=False),
    sa.Column('DIS', sa.Float(), nullable=False),
    sa.Column('RAD', sa.Float(), nullable=False),
    sa.Column('TAX', sa.Float(), nullable=False),
    sa.Column('PTRATIO', sa.Float(), nullable=False),
    sa.Column('B', sa.Float(), nullable=False),
    sa.Column('LSTAT', sa.Float(), nullable=False),
    sa.Column('MEDV', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'SECRET', 'UNKNOW', name='genderenum'), nullable=False),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.Column('introduce', sa.TEXT(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('prediction')
    # ### end Alembic commands ###
